# Microprofile server properties
server:
  port: 7987
  host: 0.0.0.0

# Change the following to true to enable the optional MicroProfile Metrics REST.request metrics
metrics:
  rest-request:
    enabled: false

# Helidon MP Security Provider - OIDC
# Security config
security:
  # Set to true for production - if set to true, clear text passwords will cause failure
  config.require-encryption: false
  properties:
    # Identity Provider - IDCS
    # FIXME: getting from kubernetes config
    idcs-uri: https://idcs-f0017ddeef0241cfbd70e057c032ff44.identity.oraclecloud.com
    idcs-client-id: e5be4d01b55c4c60b288f1068a3f20bf
    idcs-client-secret: 11218562-6203-4ad9-b138-bbd8254b3fc1
    frontend-uri: http://158.101.86.170:7987
  providers:
    - abac:
      # Adds ABAC provider - it does not require any configuration
    - oidc:
        client-id: ${security.properties.idcs-client-id}
        client-secret: ${security.properties.idcs-client-secret}
        identity-uri: ${security.properties.idcs-uri}
        audience: http://158.101.86.170:7987/
        scope-audience: http://158.101.86.170:7987
        frontend-uri: ${security.properties.frontend-uri}
        server-type: idcs
        base-scopes: openid
        redirect: true
        max-redirects: 2
        cookie-same-site: Lax
        cookie-name: "OIDC_SESSION"
    - idcs-role-mapper:
        multitenant: false
        oidc-config:
          client-id: ${security.properties.idcs-client-id}
          client-secret: ${security.properties.idcs-client-secret}
          identity-uri: ${security.properties.idcs-uri}
