# Microprofile server properties
server:
  port: 7987
  host: 0.0.0.0

# Change the following to true to enable the optional MicroProfile Metrics REST.request metrics
metrics:
  rest-request:
    enabled: false

# Security config
security:
  # Set to true for production - if set to true, clear text passwords will cause failure
  config.require-encryption: false
  properties:
    # Identity Provider - IDCS
    idcs-uri: "https://idcs-f0017ddeef0241cfbd70e057c032ff44.identity.oraclecloud.com"
    idcs-client-id: "e5be4d01b55c4c60b288f1068a3f20bf"
    idcs-client-secret: "11218562-6203-4ad9-b138-bbd8254b3fc1"
    frontend-uri: "http://138.3.214.195"
    proxy-host: ""
  providers:
    - abac:
      # Adds ABAC Provider - it does not require any configuration
    - oidc:
        client-id: "${security.properties.idcs-client-id}"
        client-secret: "${security.properties.idcs-client-secret}"
        identity-uri: "${security.properties.idcs-uri}"
        # A prefix used for custom scopes
        scope-audience: "https://ochacafe.season4"
        proxy-host: "${security.properties.proxy-host}"
        frontend-uri: "${security.properties.frontend-uri}"
        audience: "https://idcs-f0017ddeef0241cfbd70e057c032ff44.identity.oraclecloud.com:443"
        server-type: "idcs"
        idcs-roles: true
    - idcs-role-mapper:
        multitenant: false
        oidc-config:
          # we must repeat IDCS configuration, as in this case
          # IDCS serves both as open ID connect authenticator and
          # as a role mapper. Using minimal configuration here
          client-id: "${security.properties.idcs-client-id}"
          client-secret: "${security.properties.idcs-client-secret}"
          identity-uri: "${security.properties.idcs-uri}"

# Application Performance Monitoring Tracing
tracing:
  enabled: true
  name: "Helidon APM Tracer"
  service: "helidon-security"
  private-data-key: "NDMCBGA6V3BJOKVFQC3SFDYQMX7SOZBP"
  data-upload-endpoint: "https://aaaac6ptrolssaaaaaaaaaaewe.apm-agt.ap-tokyo-1.oci.oraclecloud.com"
  log-directory: "/user/apm/log"
