INSERT INTO EMPLOYEE (ID, NAME, AGE) VALUES (1, 'Patricia N. Arnold', 30);
INSERT INTO EMPLOYEE (ID, NAME, AGE) VALUES (2, 'Tammy M. Yount', 43);
INSERT INTO EMPLOYEE (ID, NAME, AGE) VALUES (3, 'Teresa W. East', 25);
INSERT INTO EMPLOYEE (ID, NAME, AGE) VALUES (4, 'Karen N. Smith', 28);
INSERT INTO EMPLOYEE (ID, NAME, AGE) VALUES (5, 'Betty J. Pennington', 50);