INSERT INTO EMPLOYEE VALUES (1, 'Patricia N. Arnold', 30);
INSERT INTO EMPLOYEE VALUES (2, 'Tammy M. Yount', 43);
INSERT INTO EMPLOYEE VALUES (3, 'Teresa W. East', 25);
INSERT INTO EMPLOYEE VALUES (4, 'Karen N. Smith', 28);
INSERT INTO EMPLOYEE VALUES (5, 'Betty J. Pennington', 50);