name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to OCIR
        uses: docker/login-action@v1
        with:
          registry: nrt.ocir.io
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ${{secrets.OCIR_FULL_PATH_EMPLOYEE }}:$GITHUB_SHA ./employee/
          docker build -t ${{secrets.OCIR_FULL_PATH_API_GATEWAY }}:$GITHUB_SHA ./api-gateway/

      - name: Push the Docker image to OCIR
        run: |
          docker push ${{ secrets.OCIR_FULL_PATH_EMPLOYEE }}:$GITHUB_SHA
          docker push ${{ secrets.OCIR_FULL_PATH_API_GATEWAY }}:$GITHUB_SHA

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        run: |
          cd deploy/kubernetes/overlays
          kustomize edit set image ${{ secrets.OCIR_FULL_PATH_EMPLOYEE }}=${{ secrets.OCIR_FULL_PATH_EMPLOYEE }}:$GITHUB_SHA
          kustomize edit set image ${{ secrets.OCIR_FULL_PATH_API_GATEWAY }}=${{ secrets.OCIR_FULL_PATH_API_GATEWAY }}:$GITHUB_SHA
          cat kustomization.yaml

      - name: Commit files
        run: |
          git config --local user.email "s001.kawamura@gmail.com"
          git config --local user.name "s001-kawamura"
          git commit -am "Bump docker tag"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
