apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: nrt.ocir.io/orasejapan/shukawam/auth
  newName: nrt.ocir.io/orasejapan/shukawam/auth
  newTag: 6de5583d42eabd7eb3227512f5b31be27922b59b
- name: nrt.ocir.io/orasejapan/shukawam/event
  newName: nrt.ocir.io/orasejapan/shukawam/event
  newTag: 6de5583d42eabd7eb3227512f5b31be27922b59b
namespace: ochacafe
