apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: nrt.ocir.io/orasejapan/shukawam/auth
  newName: nrt.ocir.io/orasejapan/shukawam/auth
  newTag: aa0864870c0f4135a3815e26e75770a6ef8ca589
namespace: ochacafe
