apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: nrt.ocir.io/orasejapan/shukawam/auth
  newName: nrt.ocir.io/orasejapan/shukawam/auth
  newTag: dd48655dffd2798d123d635f0509966e64e8669c
- name: nrt.ocir.io/orasejapan/shukawam/event
  newName: nrt.ocir.io/orasejapan/shukawam/event
  newTag: dd48655dffd2798d123d635f0509966e64e8669c
namespace: ochacafe
