apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: nrt.ocir.io/orasejapan/shukawam/auth
  newName: nrt.ocir.io/orasejapan/shukawam/auth
  newTag: 0461ef7d946ab87caa221563f8b7b24f7358385a
- name: nrt.ocir.io/orasejapan/shukawam/event
  newName: nrt.ocir.io/orasejapan/shukawam/event
  newTag: 0461ef7d946ab87caa221563f8b7b24f7358385a
namespace: ochacafe
