apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: nrt.ocir.io/orasejapan/shukawam/api-gateway
  newName: nrt.ocir.io/orasejapan/shukawam/api-gateway
  newTag: daae3232404545fb11a47cac4446b720a0d965f0
- name: nrt.ocir.io/orasejapan/shukawam/employee
  newName: nrt.ocir.io/orasejapan/shukawam/employee
  newTag: daae3232404545fb11a47cac4446b720a0d965f0
namespace: ochacafe
